version: '2'

networks:
    main:

volumes:
    config:
        driver: local
    torrents:
        driver: local

services:
    frontend:
        image: kelvinchen/seedbox:frontend
        build: Dockerfiles/frontend
        restart: always
        networks:
            - main
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - config:/config
        env_file:
            - config

    couch:
        image: tomrussell/seedbox:couch
        build: Dockerfiles/couchpotato
        restart: always
        networks:
            - main
        ports:
            - "5050:5050"
        volumes:
            - torrents:/torrents
            - config:/config
        env_file:
            - config

    deluge:
        image: tomrussell/seedbox:deluge
        build: Dockerfiles/deluge
        restart: always
        networks:
            - main
        ports:
            - "8112:8112"
            - "58846:58846"
        volumes:
            - torrents:/torrents
            - config:/config
        env_file:
            - config

    plex:
        image: kelvinchen/seedbox:plex
        build: Dockerfiles/plex
        restart: always
        network_mode: host
        volumes:
            - config:/config
            - torrents:/torrents
        env_file:
            - config

    sickrage:
        image: kelvinchen/seedbox:sickrage
        build: Dockerfiles/sickrage
        restart: always
        networks:
            - main
        volumes:
            - config:/config
            - torrents:/torrents
