version: '2'

networks:
    main:

volumes:
    config:
        driver: local
    torrents:
        driver: local

services:
    frontend:
        image: kelvinchen/seedbox:frontend
        build: Dockerfiles/frontend
        restart: always
        networks:
            - main
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - config:/config
        env_file:
            - config

    deluge:
        image: tomrussell/seedbox:deluge
        build: Dockerfiles/deluge
        restart: always
        networks:
            - main
        ports:
            - "8112:8112"
            - "58846:58846"
        volumes:
            - torrents:/torrents
            - config:/config
        env_file:
            - config

    plex:
        image: kelvinchen/seedbox:plex
        build: Dockerfiles/plex
        restart: always
        networks:
            - main
        ports:
            - "32400:32400"
            - "1900:1900"
            - "3005:3005"
            - "5353:5353"
            - "8324:8324"
            - "32410:32410"
            - "32412:32412"
            - "32413:32413"
            - "32414:32414"
            - "32469:32469"
        volumes:
            - config:/config
            - torrents:/torrents
        env_file:
            - config

    sickrage:
        image: kelvinchen/seedbox:sickrage
        build: Dockerfiles/sickrage
        restart: always
        networks:
            - main
        volumes:
            - config:/config
            - torrents:/torrents
